### ISSUE TITLE
Square shoulder issue

### ISSUE THREAD

**Issue by seinteller** [ManlyMarco/KKLB-HF_Patch#1]
![20240702224942_1](https://github.com/ManlyMarco/KKLB-HF_Patch/assets/85544685/b6f11481-5d8b-402d-8b72-bfcc1a657d79)
Hi, after I use the patch, I found the girl shoulder become square like this, Ｉ have trtied to remove the mod and the shoulder is round again.

**Comment by ManlyMarco** [comment]
Increase the graphics quality.

**Comment by seinteller** [comment]
issued fixed, thank you
